name: Sync Garmin to Notion

on:
  schedule:
    - cron: '0 1 * * *' # Daily
  workflow_dispatch:
    inputs:
      run_activities:
        description: 'Run garmin-activities.py'
        type: boolean
        default: true
      run_personal_records:
        description: 'Run personal-records.py'
        type: boolean
        default: true
      run_steps:
        description: 'Run daily-steps.py'
        type: boolean
        default: true
      run_sleep:
        description: 'Run sleep-data.py'
        type: boolean
        default: true
env:
  TZ: 'America/Montreal'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run Garmin scripts
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          NOTION_PR_DB_ID: ${{ secrets.NOTION_PR_DB_ID }}
          NOTION_STEPS_DB_ID: ${{ secrets.NOTION_STEPS_DB_ID }}
          NOTION_SLEEP_DB_ID: ${{ secrets.NOTION_SLEEP_DB_ID }}
          GARMIN_ACTIVITIES_FETCH_LIMIT: ${{ vars.GARMIN_ACTIVITIES_FETCH_LIMIT }}
          TZ: 'America/Montreal'
        run: |
          python helpers/garmin-login.py
          if [[ "${{ inputs.run_activities }}" != "false" ]]; then
            python src/workflows/garmin-activities.py
          fi
          if [[ "${{ inputs.run_personal_records }}" != "false" ]]; then
            python src/workflows/personal-records.py
          fi
          if [[ "${{ inputs.run_steps }}" != "false" ]]; then
            python src/workflows/daily-steps.py
          fi
          if [[ "${{ inputs.run_sleep }}" != "false" ]]; then
            python src/workflows/sleep-data.py
          fi
